FROM bash:latest

COPY ./git-to-svn ./svn-to-git ./scs-initialize /usr/local/bin/
COPY ./hooks.yaml /etc/webhook

RUN apk add --no-cache tini webhook subversion git git-svn

ENTRYPOINT [ "/tini", "--", "bash", "-c", "'/usr/local/bin/scs-initialize \"$@\" && /sbin/webhook -verbose -hooks /var/hooks.yaml'" "bash" ]