FROM bash:latest

COPY ./git-to-svn ./svn-to-git ./scs-initialize /usr/local/bin/
COPY ./pre-revprop-change.template /opt
COPY ./hooks.yaml /etc/webhook

RUN apk add --no-cache gettext tini webhook subversion git git-svn

ENTRYPOINT [ "/usr/local/bin/scs-initialize" ]