#! /usr/bin/env bash

scs_initialize__svn_repository() {

	local svn_path="$1"
	local svn_uri="$2"

	# 
	# Initialize SVN repo if it doesn't exist
	#
	if [[ ! -d "${svn_path}" ]] ; then
	
		svnadmin create "file://${svn_path}" \
			&& svnrdump dump "${svn_uri}" | svnadmin load "file://${svn_path}"

	fi

	#
	# Synchronize SVN repo with remote
	#
	svnsync initialize "file://${svn_path}" "${svn_path}" --allow-non-empty \
		&& svnsync synchronize "file://${svn_path}" "${svn_uri}"

}

scs_initialize__generate_authors_from_svn() {

	local svn_path="$1" ; shift 1
	local authors_file="$2" ; shift 1

	local sed_expressions=()

	while [[ "$#" != 0 ]]; do

		sed_expressions+=('-e' "$0")
		shift

	done

	#
	# Because this is running in a alpine container we're need to take in account that, to save them precious bytes, we only
	# have the shorthand options on the standard commands.
	#
	# awk (-F|--field-separator)
	# sed (-r|--regex-extended) (-e|--expression)
	#
	svn log --quiet --incremental "file://${svn_path}" \
		| awk -F"|" '{ print $2 }'                     \
		| sort | uniq                                  \
		| sed -E -e 's/(no author)/no-author/'         \
		| sed -E "${sed_expressions[@]}"               \
		| uniq                                         \
		> "${authors_file}"

}

scs_initialize__generate_authors_from_git() {

	exit 1

}

scs_initialize__git_repository() {

	local git_username="$1"
	local git_password="$2"
	local git_uri="$3"
	local git_path="$4"

	git -C "${git_path}" remote replace origin "${git_uri}"

	if [[ -Z "${git_username}" ]] ; then git -C "${git_path}" config "credential.${git_uri}.username" "${git_username}" ; fi
	if [[ -Z "${git_password}" ]] ; then git -C "${git_path}" config "credential.${git_uri}.helper" "! echo 'password=${git_password}'" ; fi

	git -C "${git_path}" pull origin

}

scs_initialize__svn_to_git() {

	local svn_path="$1"
	local git_path="$2"
	local authors="$3"

	git init --bare "${git_path}"
		&& git -C "${git_path}" svn init "file://${svn_path}" \
			--stdlayout                                       \
			--use-svnsync-props                               \
			--authors-file="${authors}"                       \
			--prefix "svn"                                    \
		&& git -C "${git_path}" svn fetch

}

scs_initialize__git_to_svn() {

	#
	# With our populated git repo do an initial git svn dcommit of everything
	#

	exit 1

}

scs_initialize__start_webhooks() { 	

	exit 1

}

scs_initialize__help() {

	printf '%b\n' \
		'scs-initialize - Initilization and start-up script for a docker container with  ' \
		'                 the goal of synchronizing a SVN and GIT repository             ' \
		'                                                                                ' \
		'Usage:                                                                          ' \
		'  scs-initialize [options]                                                      ' \
		'  scs-initialize [direction] [options] [author expressions]                     ' \
		'                                                                                ' \
		'Direction: <svn-to-git|git-to-svn>                                              ' \
		'  Definese the direction of the synchronization after initalization, if no      ' \
		'  direction is provided it is assumed that the repositories are in sync and no  ' \
		'  action is neccesary after initalization.                                      ' \
		'                                                                                ' \
		'Author expressions: <sed expression>...                                         ' \
		'  Depending on the initlaization direction we want to generate an authors file  ' \
		'  on using the provided username/email combination. These sed expressions allow ' \
		'  you to maniulate the output here. The result should be an authors file        ' \
		'                                                                                ' \
		'Options:                                                                        ' \
		'  --svn <username> <password> <uri>                                             ' \
		'  --git <username> <password> <uri>                                             ' \
		'                                                                                '

}

scs_initialize__main() {

	set -e
	set -o pipefail
	set -o errtrace

	local svn_path="${SCS_SVN_PATH:=/var/svn}"
	local git_path="${SCS_GIT_PATH:=/var/git}"

	local svn_username="${SCS_SVN_USERNAME}"
	local svn_password="${SCS_SVN_PASSWORD}" 
	local svn_uri="${SCS_SVN_URI}"

	local git_username="${SCS_GIT_USERNAME}"
	local git_password="${SCS_GIT_PASSWORD}"
	local git_uri="${SCS_GIT_URI}"
	
	local initalization_direction
	
	
	case "$1" in
		"git-to-svn") initalization_direction="$1" ; shift 1 ;;
		"svn-to-git") initalization_direction="$1" ; shift 1 ;;
	esac

	while [[ $# != 0 ]]; do

		case "$1" in
			--svn) svn_username="$2" ; svn_password="$3" ; svn_uri="$4" ; shift 4 ;;
			--git) git_username="$2" ; git_passowrd="$3" ; git_uri="$4" ; shift 4 ;;
			"-?" | --help) scs_initialize__help ; exit ;;
			*) {
				printf "[ initialize ] Unknown option [ %s ]" "$1" >&2
				exit 1
			}
		esac

	done

	if   [[ -z "${svn_uri}" ]] ; then printf "[ initialize ] No remote SVN uri was provided." >&2 ; exit 1
	elif [[ -z "${git_uri}" ]] ; then printf "[ initialize ] No remote GIT uri was provided." >&2 ; exit 1
	fi

	export SVS_SVN_PATH="${svn_path}"
	export SCS_GIT_PATH="${git_path}"
	
	export SCS_AUTHORS="${SCS_AUTHORS:=/var/AUTHORS}"

	export SCS_SVN_USERNAME="${svn_username}"
	export SCS_SVN_PASSWORD="${svn_password}"
	export SCS_SVN_URI="${svn_uri}"
	
	export SCS_GIT_USERNAME="${git_username}"
	export SCS_GIT_PASSWORD="${git_password}"
	export SCS_GIT_URI="${git_uri}"

	if [[ "${initalization_direction}" = "svn-to-git" ]] ; then 
		
		scs_initialize__svn_repository "${svn_username}" "${svn_password}" "${svn_uri}" "${svn_path}"
		scs_initialize__generate_authors_from_svn "${svn_path}" "${SCS_AUTHORS}"
		scs_initialize__svn_to_git "${svn_path}" "${git_path}"
		
		exit

	elif [[ "${initalization_direction}" = "git-to-svn" ]] ; then 

		scs_initialize__git_repository "${git_username}" "${git_password}" "${git_uri}" "${git_path}"
		scs_initialize__generate_authors_from_git "${git_path}" "${SCS_AUTHORS}"
		scs_initialize__git_to_svn "${git_path}" "${svn_path}"

		exit

	elif [[ -z "${initalization_direction}" ]] ; then
	
		scs_initialize__svn_repository "${svn_username}" "${svn_password}" "${svn_uri}" "${svn_path}"
		scs_initialize__git_repository "${git_username}" "${git_password}" "${git_uri}" "${git_path}"
		scs_initialize__start_webhooks

		exit

	fi

	exit 1

}

(return 0 2>/dev/null) || scs_initialize__main "$@"
